"""All 21 PVC recipients: primary narrative briefs, separate unverified life facts and dates."""
import gzip,json,re
from pathlib import Path
from bs4 import BeautifulSoup
R=Path(__file__).resolve().parent;D=R/'data'
entries=[
(1,'Somnath Sharma','Major','4 Kumaon','1947-11-03','Badgam','He led his company while it was attacked from several directions near Srinagar. Moving between positions under fire, he directed the defence until a mortar explosion killed him. The memorial credits his leadership with sustaining resistance and delaying the attack.'),
(5,'Jadunath Singh','Naik','1 Rajput','1948-02-06','Tain Dhar, Naushera','He commanded a post that faced repeated attacks and suffered severe casualties. Although wounded, he continued resisting and charged the attackers with a Sten gun. He died during the defence.'),
(6,'Rama Raghoba Rane','Second Lieutenant','Bombay Sappers','1948-04-08','Naushera–Rajouri road','He led engineers clearing mines and obstructions under shellfire. Wounded during the action, he continued helping tanks negotiate the route. The memorial describes his work as crucial to opening a safe lane for the advance.'),
(7,'Piru Singh','Company Havildar Major','6 Rajputana Rifles','1948-07-18','Tithwal','During an assault on a defended hill, his section suffered heavy losses. He continued attacking machine-gun positions despite wounds and the loss of his companions, dying during the action.'),
(8,'Karam Singh','Lance Naik','1 Sikh','1948-10-13','Richhmar Gali','He kept his section fighting through repeated attacks after bombardment damaged its defences. Despite wounds, he moved between positions, helped comrades and sustained their resistance. His section held the locality.'),
(9,'Gurbachan Singh Salaria','Captain','3/1 Gorkha Rifles','1961-12-05','Elizabethville, Congo','During a United Nations mission, he confronted Katangese forces near a roadblock. He led a close assault despite being wounded and died from his injuries. The memorial credits the action with protecting the UN headquarters.'),
(10,'Dhan Singh Thapa','Major','1/8 Gorkha Rifles','1962-10-20','Ladakh','He commanded an isolated post facing repeated Chinese attacks. The defenders continued resisting after heavy bombardment and losses. He fought at close quarters before being overpowered. His award was not posthumous.'),
(11,'Joginder Singh','Subedar','1 Sikh','1962-10-23','Bum La','His platoon resisted successive Chinese assaults. Wounded in the thigh, he refused evacuation and continued directing the defence. When ammunition ran out, he led the remaining men in close combat.'),
(12,'Shaitan Singh','Major','13 Kumaon','1962-11-18','Rezang La','He commanded a company attacked by a much larger Chinese force. Moving between platoon positions under fire, he continued encouraging his soldiers despite severe wounds and died during the battle.'),
(13,'Ardeshir Burzorji Tarapore','Lieutenant Colonel','Poona Horse','1965-09-11','Phillora and Sialkot sector','He led his armoured regiment through several engagements during the 1965 war. Despite injury, he remained in command as it fought for successive objectives. He died when his tank was hit. The cited actions extend over several days.'),
(14,'Abdul Hamid','Company Quarter Master Havildar','4 Grenadiers','1965-09-10','Khem Karan sector','He commanded a recoilless-gun detachment that engaged Pakistani tanks. Repeatedly changing position under fire, he continued fighting until mortally wounded. The page’s narrative dates this action to 1965, while its displayed header incorrectly shows 1967.'),
(15,'Albert Ekka','Lance Naik','14 Guards','1971-12-04','Gangasagar','During an attack on fortified positions, he silenced machine-gun fire obstructing his company’s advance. Despite serious injury, he continued attacking another position. The memorial dates the action to 4 December; the date requires reconciliation with other accounts.'),
(16,'Nirmal Jit Singh Sekhon','Flying Officer','18 Squadron','1971-12-14','Srinagar airfield','He took off in a Gnat while Pakistani aircraft were attacking Srinagar airfield. He engaged the attackers despite their numerical advantage. His aircraft was shot down during the fight, and he received the award posthumously.'),
(17,'Hoshiar Singh','Major','3 Grenadiers','1971-12-15','Jarpal','He led his company in capturing a defended position and resisted subsequent counterattacks. Despite wounds, he moved between trenches to direct his soldiers. When a machine-gun crew was hit, he operated the weapon himself.'),
(18,'Arun Khetarpal','Second Lieutenant','Poona Horse','1971-12-16','Shakargarh sector','He moved his tanks to reinforce another squadron, fighting through resistance en route. In the subsequent tank battle, he continued engaging the enemy despite injury and orders to withdraw. He died when his Centurion was hit again.'),
(19,'Bana Singh','Naib Subedar','8 Jammu and Kashmir Light Infantry','1987-06-26','Quaid Post, Siachen','He volunteered for an assault on a Pakistani-held position in extreme mountain conditions. His team climbed a difficult ice approach and attacked the defenders at close quarters. The memorial credits his leadership in capturing the post.'),
(20,'Ramaswamy Parameswaran','Major','8 Mahar','1987-11-25','Sri Lanka','After militants ambushed his returning search column, he organised a counterattack. Shot in the chest during close fighting, he continued issuing orders and inspiring his soldiers until he died.'),
(21,'Manoj Kumar Pandey','Lieutenant','1/11 Gorkha Rifles','1999-07-03','Khalubar ridge','He led attacks on bunkers obstructing his company’s advance in Batalik. Despite multiple wounds, he continued until killed. The narrative dates the action to 3 July, although the page’s header displays 9 July.'),
(22,'Yogendra Singh Yadav','Grenadier','18 Grenadiers','1999-07-03','Tiger Hill','As part of an assault platoon, he climbed a steep approach under fire and attacked fortified positions. Despite multiple bullet wounds, he continued fighting, helping the rest of the platoon advance. The memorial spells his first name “Yogender.”'),
(23,'Sanjay Kumar','Rifleman','13 Jammu and Kashmir Rifles','1999-07-04','Flat Top, Mushkoh Valley','Leading his company’s approach, he attacked an enemy position after coming under fire. Although seriously wounded, he continued fighting with a captured machine gun. The narrative dates the action to 4 July; the header instead displays 12 December.'),
(24,'Vikram Batra','Captain','13 Jammu and Kashmir Rifles','1999-07-07','Point 5140 and Point 4875','He led assaults during the Kargil campaign, including actions at Point 5140 and Point 4875. During the latter engagement he continued leading despite serious wounds and died in the fighting. The memorial credits his example with inspiring his troops to capture the objective.')
]
bios=json.loads((D/'biographical-facts.json').read_text());out=[]
for n,name,rank,unit,date,location,story in entries:
 s=BeautifulSoup(gzip.decompress((R/f'raw/nwm-profile-{n}.bin.gz').read_bytes()),'html.parser')
 header=s.select_one('.paramYoddhaPhoto .year').get_text(' ',strip=True)
 alias={'Ardeshir Burzorji Tarapore':'Ardeshir Tarapore','Hoshiar Singh':'Hoshiar Singh Dahiya','Ramaswamy Parameswaran':'Ramaswamy Parameshwaran'}.get(name,name)
 key=re.sub(r'[^a-z]','',alias.lower())
 matches=[x for x in bios if re.sub(r'[^a-z]','',x['name'].lower())==key]
 b=matches[0] if len(matches)==1 else None
 out.append({'id':'pvc-'+str(n),'name':name,'rankAtAction':rank,'unitAtAction':unit,'service':'Indian Air Force' if n==16 else 'Indian Army','medal':'Param Vir Chakra','posthumous':'Posthumous' in s.select_one('.paramYoddhaPhoto h3').get_text(),'actionDateFromNarrative':date,'displayedDateRaw':header,'dateNote':'Narrative date only; award announcement/gazette year requires separate evidence. Multi-day actions are not reduced to this date.','location':location,'story':story,'biographicalFactsRaw':b['factsRaw'] if b else None,'biographySourceUrl':b['sourceUrl'] if b else None,'biographyVerification':'secondary_unverified' if b else 'not_matched','sourceId':'nwm-profile-'+str(n),'sourceUrl':'https://nationalwarmemorial.gov.in/param-yoddhas/details/'+str(n),'locator':'Profile narrative and date header','publicationStatus':'editorial_review_required'})
(D/'pvc-recipient-profiles.json').write_text(json.dumps(out,ensure_ascii=False,indent=2));print('PVC profiles',len(out),'secondary biographical matches',sum(bool(x['biographicalFactsRaw']) for x in out))
