import Link from "next/link";
import { PageHeader, PageShell } from "@/components/PageShell";
import { CollectionToolbar } from "@/components/CollectionToolbar";
import { Pagination } from "@/components/Pagination";
import { parseCollectionQuery } from "@/lib/domain/query";
import { listPublicEntities } from "@/lib/repositories/collections";
import { prisma } from "@/lib/db";
import { CompareTray } from "@/components/CompareTray";
export const dynamic = "force-dynamic";
export default async function ArsenalPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const raw = await searchParams; const query = parseCollectionQuery(raw); const result = await listPublicEntities("Equipment", query, prisma);
  const [domains, categories, statuses] = await Promise.all([prisma.equipment.findMany({ where: { publicationStatus: "PUBLISHED", contentKind: "EDITORIAL", reviewedAt: { not: null }, reviewedBy: { not: null } }, distinct: ["domain"], select: { domain: true }, orderBy: { domain: "asc" } }), prisma.equipment.findMany({ where: { publicationStatus: "PUBLISHED", contentKind: "EDITORIAL", reviewedAt: { not: null }, reviewedBy: { not: null } }, distinct: ["category"], select: { category: true }, orderBy: { category: "asc" } }), prisma.equipment.findMany({ where: { publicationStatus: "PUBLISHED", contentKind: "EDITORIAL", reviewedAt: { not: null }, reviewedBy: { not: null } }, distinct: ["serviceStatus"], select: { serviceStatus: true }, orderBy: { serviceStatus: "asc" } })]);
  const params = new URLSearchParams(Object.entries(raw).flatMap(([key, value]) => value ? [[key, Array.isArray(value) ? value[0] : value]] : []));
  return <PageShell><PageHeader title="Arsenal" description="Reviewed platforms, weapons, and military technology." /><div className="mb-8"><CollectionToolbar fields={[{ key: "domain", label: "Domain", options: domains.map((row) => row.domain) }, { key: "category", label: "Category", options: categories.map((row) => row.category) }, { key: "status", label: "Service status", options: statuses.map((row) => row.serviceStatus) }]} /></div><p className="mb-4 text-sm text-muted-foreground">{result.total} reviewed records · showing {result.items.length}</p><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{result.items.map((equipment) => <Link key={equipment.id} href={equipment.href} className="rounded-lg border border-border/60 bg-card p-5 transition-colors hover:border-primary/60"><p className="text-xs uppercase text-primary">{equipment.facts[0]?.value}</p><h2 className="mt-2 text-xl font-semibold">{equipment.title}</h2><p className="mt-2 line-clamp-3 text-sm text-muted-foreground">{equipment.summary}</p></Link>)}</div>{result.items.length === 0 && <p className="rounded-lg border border-dashed p-8 text-center text-muted-foreground">No reviewed arsenal records match these filters.</p>}<div className="mt-8"><CompareTray options={result.items.map((item) => ({ slug: item.slug, title: item.title }))} /><div className="mt-8"><Pagination page={result.page} pageCount={result.pageCount} params={params} /></div></div></PageShell>;
}
