[project]
name = "factory"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dagster>=1.13.20",
    "dagster-webserver>=1.13.20",
    "dbt-core~=1.4.0",
    "dbt-sqlite~=1.4.0",
    "ollama>=0.6.2",
    "prisma>=0.15.0",
    "pydantic>=2.13.5",
    "pyyaml>=6.0.3",
]

[project.scripts]
factory = "factory:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
