import { PageHeader, PageShell } from "@/components/PageShell";
import { CollectionToolbar } from "@/components/CollectionToolbar";
import { Pagination } from "@/components/Pagination";
import { parseCollectionQuery } from "@/lib/domain/query";
import { listPublicEntities } from "@/lib/repositories/collections";
import { prisma } from "@/lib/db";
import { CollectionChronology } from "@/components/CollectionChronology";
export const dynamic = "force-dynamic";
export default async function ConflictsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) { const raw = await searchParams; const result = await listPublicEntities("Conflict", { ...parseCollectionQuery(raw), sort: "date" }, prisma); const params = new URLSearchParams(Object.entries(raw).flatMap(([key, value]) => value ? [[key, Array.isArray(value) ? value[0] : value]] : [])); const years = ["1947", "1948", "1961", "1962", "1965", "1971", "1984", "1999"]; const chronology = result.items.map((conflict) => ({ id: conflict.id, date: conflict.facts.find((fact) => fact.label === "Start")?.value ?? "Date classified", title: conflict.title, description: conflict.summary, href: conflict.href })); return <PageShell><PageHeader title="Conflicts" description="Historical conflicts and campaigns." actions={<div className="w-full max-w-2xl"><CollectionToolbar fields={[{ key: "year", label: "Year / period", options: years }]} /></div>} /><div className="max-w-4xl"><CollectionChronology events={chronology} /></div>{result.items.length === 0 && <p className="mt-6 rounded-lg border border-dashed p-8 text-center text-muted-foreground">No timeline entries match the selected filters.</p>}<div className="mt-8"><Pagination page={result.page} pageCount={result.pageCount} params={params} /></div></PageShell>; }
