"use client";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
export type CollectionOption = string | { value: string; label: string };
export function CollectionToolbar({ fields, className = "" }: { fields: Array<{ key: string; label: string; options: CollectionOption[] }>; className?: string }) {
  const router = useRouter(); const pathname = usePathname(); const search = useSearchParams();
  const change = (key: string, value: string) => { const params = new URLSearchParams(search.toString()); value ? params.set(key, value) : params.delete(key); if (key === "domain") { params.delete("category"); params.delete("use"); } params.delete("page"); router.push(`${pathname}?${params.toString()}`); };
  const clear = () => router.push(pathname);
  const fieldKeys = new Set(fields.map((field) => field.key));
  const labelFor = (field: { options: CollectionOption[] }, value: string) => { const selected = field.options.find((option) => typeof option === "string" ? option === value : option.value === value); return typeof selected === "string" ? selected : selected?.label ?? value; };
  const activeFilters = Array.from(search.entries()).filter(([key]) => key !== "page" && fieldKeys.has(key));
  return <div className={`space-y-3 ${className}`}><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{fields.map((field) => <label key={field.key} className="text-sm text-muted-foreground">{field.label}<select aria-label={field.label} value={search.get(field.key) ?? ""} onChange={(event) => change(field.key, event.target.value)} className="mt-1 w-full rounded border border-border bg-card px-3 py-2 text-foreground"><option value="">All</option>{field.options.map((option) => { const value = typeof option === "string" ? option : option.value; const label = typeof option === "string" ? option : option.label; return <option key={value} value={value}>{label}</option>; })}</select></label>)}</div><div className="flex flex-wrap items-center gap-2 text-xs">{activeFilters.map(([key, value]) => { const field = fields.find((item) => item.key === key); return <button key={`${key}-${value}`} type="button" onClick={() => change(key, "")} className="rounded-full border border-primary/50 px-2 py-1 text-primary">{field?.label ?? key}: {field ? labelFor(field, value) : value} ×</button>; })}{activeFilters.length > 0 && <button type="button" onClick={clear} className="text-muted-foreground underline">Clear all</button>}</div></div>;
}
