"""Curated primary-source evidence used to audit the equipment snapshot.

These claims supplement, but do not silently overwrite, the source-table wording.
The scraper exports them as separately identifiable official-source records and
uses the aliases to mark related scraped rows as having an official evidence
source available.
"""

from __future__ import annotations


OFFICIAL_CLAIMS = [
    {
        "claim_id": "drdo_akash_operational",
        "system_aliases": ["Akash"],
        "branch_aliases": ["Indian Army", "Indian Air Force"],
        "field": "status_and_role",
        "value": "Inducted and operational with the Indian Army and Indian Air Force; short-range surface-to-air missile system.",
        "publisher": "DRDO",
        "title": "Akash",
        "url": "https://drdo.gov.in/drdo/en/offerings/products/akash",
        "published_date": "Not stated",
    },
    {
        "claim_id": "drdo_brahmos_operational",
        "system_aliases": ["BrahMos", "Brahmos"],
        "branch_aliases": ["Indian Army", "Indian Navy"],
        "field": "status_and_role",
        "value": "Inducted and operational with the Indian Navy and Indian Army; land-, sea-, and air-launched supersonic cruise-missile system.",
        "publisher": "DRDO",
        "title": "BrahMos",
        "url": "https://drdo.gov.in/drdo/en/offerings/products/brahmos",
        "published_date": "Not stated",
    },
    {
        "claim_id": "drdo_mrsam_users",
        "system_aliases": ["MRSAM", "MR-SAM"],
        "branch_aliases": ["Indian Army", "Indian Air Force"],
        "field": "status_and_users",
        "value": "Jointly developed with IAI for IAF and Army Air Defence; firing units have been delivered to both users.",
        "publisher": "DRDO",
        "title": "MRSAM",
        "url": "https://drdo.gov.in/drdo/en/offerings/products/mrsam",
        "published_date": "Not stated",
    },
    {
        "claim_id": "drdo_guided_pinaka_induction_recommendation",
        "system_aliases": ["Pinaka"],
        "branch_aliases": ["Indian Army"],
        "field": "development_status",
        "value": "Guided Pinaka development and qualification activities were reported complete, with the trial team recommending induction; upgraded in-service launchers remained under evaluation.",
        "publisher": "DRDO",
        "title": "Guided Pinaka Rocket System",
        "url": "https://drdo.gov.in/drdo/en/offerings/products/guided-pinaka-rocket-system",
        "published_date": "Not stated",
    },
    {
        "claim_id": "pib_tejas_mk1a_contract",
        "system_aliases": ["Tejas Mk1A", "HAL Tejas"],
        "branch_aliases": ["Indian Air Force"],
        "field": "contract_and_delivery",
        "value": "MoD signed a contract for 97 LCA Mk1A aircraft on 25 September 2025; deliveries were stated to start in 2027–28 and complete over six years.",
        "publisher": "Ministry of Defence / PIB",
        "title": "MoD signs ₹62,370 crore contract with HAL for procurement of 97 LCA Mk1A aircraft for IAF",
        "url": "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2171108&lang=2&reg=3",
        "published_date": "25 September 2025",
    },
    {
        "claim_id": "pib_acada_contract",
        "system_aliases": ["ACADA"],
        "branch_aliases": ["Indian Army"],
        "field": "contract_and_quantity",
        "value": "Contract signed on 25 February 2025 for 223 Automatic Chemical Agent Detection and Alarm systems designed by DRDO's Defence Research and Development Establishment and procured from L&T.",
        "publisher": "Ministry of Defence / PIB",
        "title": "Indian Army procures critical CBRN defence equipment",
        "url": "https://www.pib.gov.in/pressreleasepage.aspx?lang=2&prid=2106362&reg=48",
        "published_date": "26 February 2025",
    },
    {
        "claim_id": "pib_atags_contract",
        "system_aliases": ["ATAGS", "Advanced Towed Artillery Gun System"],
        "branch_aliases": ["Indian Army"],
        "field": "contract_and_role",
        "value": "MoD signed contracts on 26 March 2025 for 155 mm/52 calibre ATAGS and 6x6 gun-towing vehicles; ATAGS is intended to replace vintage smaller-calibre guns.",
        "publisher": "Ministry of Defence / PIB",
        "title": "MoD inks ₹6,900 crore contracts for ATAGS and HMV 6x6 gun-towing vehicles",
        "url": "https://www.pib.gov.in/Pressreleaseshare.aspx?PRID=2115365&lang=2&reg=48",
        "published_date": "26 March 2025",
    },
    {
        "claim_id": "pib_namis_contract",
        "system_aliases": ["NAMIS", "NAMICA"],
        "branch_aliases": ["Indian Army"],
        "field": "contract_and_role",
        "value": "MoD signed a contract on 27 March 2025 for the NAMIS tracked anti-tank weapon platform; the system is intended to modernize mechanized-infantry anti-tank capability.",
        "publisher": "Ministry of Defence / PIB",
        "title": "MoD inks contracts for NAMIS Tracked and light vehicles",
        "url": "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2115804&lang=2&reg=48&s=09",
        "published_date": "27 March 2025",
    },
    {
        "claim_id": "pib_nag_mk2_trials",
        "system_aliases": ["Nag Mk 2"],
        "branch_aliases": ["Indian Army"],
        "field": "trial_status",
        "value": "Field evaluation trials were reported successful on 13 January 2025 and the weapon system was described as ready for induction.",
        "publisher": "Ministry of Defence / PIB",
        "title": "Successful field evaluation trials of Nag Mk 2",
        "url": "https://www.pib.gov.in/PressReleaseIframePage.aspx?PRID=2092585&lang=2&reg=48",
        "published_date": "13 January 2025",
    },
    {
        "claim_id": "pib_invar_contract",
        "system_aliases": ["INVAR", "3UBK-Invar", "9M119"],
        "branch_aliases": ["Indian Army"],
        "field": "contract_and_role",
        "value": "MoD and BDL signed a ₹2,095.70 crore contract on 13 November 2025 for INVAR anti-tank missiles for T-90 tanks.",
        "publisher": "Ministry of Defence / PIB",
        "title": "MoD and BDL sign contract for INVAR anti-tank missiles",
        "url": "https://www.pib.gov.in/PressReleseDetailm.aspx?PRID=2189725&lang=2&reg=48",
        "published_date": "13 November 2025",
    },
    {
        "claim_id": "pib_ins_surat_nilgiri_vaghsheer",
        "system_aliases": ["INS Surat", "INS Nilgiri", "INS Vaghsheer"],
        "branch_aliases": ["Indian Navy"],
        "field": "commissioning_date",
        "value": "The three platforms were commissioned on 15 January 2025.",
        "publisher": "Ministry of Defence / PIB",
        "title": "PM dedicates INS Surat, INS Nilgiri and INS Vaghsheer",
        "url": "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2093018&lang=1&reg=20",
        "published_date": "15 January 2025",
    },
    {
        "claim_id": "pib_ins_arnala",
        "system_aliases": ["INS Arnala", "Arnala class"],
        "branch_aliases": ["Indian Navy"],
        "field": "commissioning_role_dimensions",
        "value": "INS Arnala was commissioned on 18 June 2025; it is an ASW shallow-water craft, 77 m long and over 1,490 tonnes, designed for subsurface surveillance/interdiction, search and rescue, and low-intensity maritime operations.",
        "publisher": "Ministry of Defence / PIB",
        "title": "INS Arnala commissioned into the Indian Navy",
        "url": "https://www.pib.gov.in/Pressreleaseshare.aspx?PRID=2137263&lang=2&reg=48",
        "published_date": "18 June 2025",
    },
    {
        "claim_id": "pib_ins_nistar",
        "system_aliases": ["INS Nistar", "Nistar class"],
        "branch_aliases": ["Indian Navy"],
        "field": "commissioning_role",
        "value": "INS Nistar, the first indigenously designed and constructed diving support vessel, was commissioned on 18 July 2025 for deep-sea diving and rescue operations.",
        "publisher": "Ministry of Defence / PIB",
        "title": "INS Nistar commissioned in Vizag",
        "url": "https://www.pib.gov.in/PressReleaseIframePage.aspx?PRID=2145766",
        "published_date": "18 July 2025",
    },
    {
        "claim_id": "pib_ins_tamal",
        "system_aliases": ["INS Tamal", "Talwar class"],
        "branch_aliases": ["Indian Navy"],
        "field": "commissioning_date",
        "value": "INS Tamal was commissioned on 1 July 2025; it is the eighth Project 1135.6 multi-role stealth frigate and second additional Tushil-class ship.",
        "publisher": "Ministry of Defence / PIB",
        "title": "INS Tamal commissioned into the Indian Navy",
        "url": "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2141361&lang=2&reg=48",
        "published_date": "1 July 2025",
    },
    {
        "claim_id": "pib_ins_udaygiri_himgiri",
        "system_aliases": ["INS Udaygiri", "INS Himgiri", "Udaygiri class", "Himgiri class"],
        "branch_aliases": ["Indian Navy"],
        "field": "commissioning_date",
        "value": "INS Udaygiri and INS Himgiri were commissioned on 26 August 2025 as Project 17A stealth frigates.",
        "publisher": "Ministry of Defence / PIB",
        "title": "INS Udaygiri and INS Himgiri commissioned",
        "url": "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2160941&lang=1&reg=37",
        "published_date": "26 August 2025",
    },
]


OFFICIAL_SUPPLEMENT_RECORDS = [
    {
        "system_name": "ACADA",
        "branch": "Indian Army",
        "domain": "CBRN defence equipment",
        "category": "Chemical agent detection and alarm",
        "status": "on_order",
        "source_status": "Contract signed 25 February 2025 for 223 systems",
        "status_as_of": "2025-02-25",
        "commissioned_or_inducted_date": "Not documented",
        "retired_or_decommissioned_date": "Not documented",
        "quantity": 223,
        "quantity_min": 223,
        "quantity_max": 223,
        "quantity_raw": "223 systems",
        "quantity_values": "[223]",
        "role_purpose": "Detect chemical warfare agents and programmed toxic industrial chemicals in sampled air.",
        "specifications": '{"principle": "Ion Mobility Spectrometry", "detectors": "Two IMS cells"}',
        "dimensions": "Not documented",
        "make_manufacturer": "L&T; designed by DRDO Defence Research and Development Establishment, Gwalior",
        "country_of_origin": "India",
        "operators": "Indian Army",
        "notes": "Official contract evidence; induction date and detailed dimensions were not stated.",
        "claim_id": "pib_acada_contract",
    },
    {
        "system_name": "ATAGS",
        "branch": "Indian Army",
        "domain": "artillery",
        "category": "155 mm/52 calibre towed artillery gun",
        "status": "on_order",
        "source_status": "MoD contracts signed 26 March 2025",
        "status_as_of": "2025-03-26",
        "commissioned_or_inducted_date": "Not documented",
        "retired_or_decommissioned_date": "Not documented",
        "quantity": None,
        "quantity_min": None,
        "quantity_max": None,
        "quantity_raw": "Not documented",
        "quantity_values": "[]",
        "role_purpose": "Replace vintage smaller-calibre guns and enhance long-range artillery firepower.",
        "specifications": '{"calibre": "155 mm/52 calibre"}',
        "dimensions": "Not documented",
        "make_manufacturer": "Bharat Forge; DRDO Armament Research and Development Establishment",
        "country_of_origin": "India",
        "operators": "Indian Army",
        "notes": "Official contract evidence; public release did not state the contracted quantity.",
        "claim_id": "pib_atags_contract",
    },
    {
        "system_name": "NAMIS (Tr)",
        "branch": "Indian Army",
        "domain": "anti-tank weapon systems",
        "category": "Tracked anti-tank weapon platform",
        "status": "on_order",
        "source_status": "Contract signed 27 March 2025",
        "status_as_of": "2025-03-27",
        "commissioned_or_inducted_date": "Not documented",
        "retired_or_decommissioned_date": "Not documented",
        "quantity": None,
        "quantity_min": None,
        "quantity_max": None,
        "quantity_raw": "Not documented",
        "quantity_values": "[]",
        "role_purpose": "Modernize the anti-tank capability of mechanized infantry.",
        "specifications": "Not documented",
        "dimensions": "Not documented",
        "make_manufacturer": "Armoured Vehicle Nigam Limited; developed by DRDO Defence Research & Development Laboratory",
        "country_of_origin": "India",
        "operators": "Indian Army",
        "notes": "Official contract evidence; quantity was not stated in the cited release.",
        "claim_id": "pib_namis_contract",
    },
    {
        "system_name": "Nag Mk 2",
        "branch": "Indian Army",
        "domain": "anti-tank missiles",
        "category": "Third-generation fire-and-forget anti-tank guided missile",
        "status": "under_trials",
        "source_status": "Field evaluation trials successful; ready for induction",
        "status_as_of": "2025-01-13",
        "commissioned_or_inducted_date": "Not documented",
        "retired_or_decommissioned_date": "Not documented",
        "quantity": None,
        "quantity_min": None,
        "quantity_max": None,
        "quantity_raw": "Not documented",
        "quantity_values": "[]",
        "role_purpose": "Fire-and-forget anti-tank engagement.",
        "specifications": "Not documented",
        "dimensions": "Not documented",
        "make_manufacturer": "DRDO",
        "country_of_origin": "India",
        "operators": "Indian Army",
        "notes": "Official field-evaluation result; ready-for-induction wording does not establish completed induction.",
        "claim_id": "pib_nag_mk2_trials",
    },
    {
        "system_name": "INVAR",
        "branch": "Indian Army",
        "domain": "anti-tank missiles",
        "category": "Laser-guided tank-launched anti-tank missile",
        "status": "on_order",
        "source_status": "Contract signed 13 November 2025",
        "status_as_of": "2025-11-13",
        "commissioned_or_inducted_date": "Not documented",
        "retired_or_decommissioned_date": "Not documented",
        "quantity": None,
        "quantity_min": None,
        "quantity_max": None,
        "quantity_raw": "Not documented",
        "quantity_values": "[]",
        "role_purpose": "Enhance the lethality of T-90 armoured regiments.",
        "specifications": '{"guidance": "Laser-guided"}',
        "dimensions": "Not documented",
        "make_manufacturer": "Bharat Dynamics Limited",
        "country_of_origin": "India / Russia-origin system family",
        "operators": "Indian Army",
        "notes": "Official contract evidence; quantity and delivery schedule were not stated in the cited release.",
        "claim_id": "pib_invar_contract",
    },
    {
        "system_name": "LCA Tejas Mk1A",
        "branch": "Indian Air Force",
        "domain": "aircraft",
        "category": "Multirole fighter",
        "status": "on_order",
        "source_status": "Contract signed 25 September 2025; deliveries scheduled from 2027–28",
        "status_as_of": "2025-09-25",
        "commissioned_or_inducted_date": "Not documented",
        "retired_or_decommissioned_date": "Not documented",
        "quantity": 97,
        "quantity_min": 97,
        "quantity_max": 97,
        "quantity_raw": "97 aircraft (68 fighters and 29 twin-seaters)",
        "quantity_values": "[97, 68, 29]",
        "role_purpose": "Multirole fighter aircraft.",
        "specifications": '{"indigenous_content": ">64%", "radar": "UTTAM AESA"}',
        "dimensions": "Not documented",
        "make_manufacturer": "Hindustan Aeronautics Limited; ADA/DRDO ecosystem",
        "country_of_origin": "India",
        "operators": "Indian Air Force",
        "notes": "Official procurement supplement; quantity is a contract quantity, not an in-service count.",
        "claim_id": "pib_tejas_mk1a_contract",
    },
    {
        "system_name": "INS Surat",
        "branch": "Indian Navy",
        "domain": "ships and submarines",
        "category": "Project 15B guided-missile destroyer",
        "status": "in_service",
        "source_status": "Commissioned 15 January 2025",
        "status_as_of": "2025-01-15",
        "commissioned_or_inducted_date": "2025-01-15",
        "retired_or_decommissioned_date": "Not documented",
        "quantity": 1,
        "quantity_min": 1,
        "quantity_max": 1,
        "quantity_raw": "1 named ship",
        "quantity_values": "[1]",
        "role_purpose": "Frontline guided-missile destroyer.",
        "specifications": "Not documented",
        "dimensions": "Not documented",
        "make_manufacturer": "Mazagon Dock Shipbuilders Limited / Indian Navy Warship Design Bureau",
        "country_of_origin": "India",
        "operators": "Indian Navy",
        "notes": "Official commissioning supplement; detailed technical fields remain source-dependent.",
        "claim_id": "pib_ins_surat_nilgiri_vaghsheer",
    },
    {
        "system_name": "INS Nilgiri",
        "branch": "Indian Navy",
        "domain": "ships and submarines",
        "category": "Project 17A stealth frigate",
        "status": "in_service",
        "source_status": "Commissioned 15 January 2025",
        "status_as_of": "2025-01-15",
        "commissioned_or_inducted_date": "2025-01-15",
        "retired_or_decommissioned_date": "Not documented",
        "quantity": 1,
        "quantity_min": 1,
        "quantity_max": 1,
        "quantity_raw": "1 named ship",
        "quantity_values": "[1]",
        "role_purpose": "Frontline stealth frigate.",
        "specifications": "Not documented",
        "dimensions": "Not documented",
        "make_manufacturer": "Mazagon Dock Shipbuilders Limited / Indian Navy Warship Design Bureau",
        "country_of_origin": "India",
        "operators": "Indian Navy",
        "notes": "Official commissioning supplement; detailed technical fields remain source-dependent.",
        "claim_id": "pib_ins_surat_nilgiri_vaghsheer",
    },
    {
        "system_name": "INS Vaghsheer",
        "branch": "Indian Navy",
        "domain": "ships and submarines",
        "category": "Project 75 Scorpene-class submarine",
        "status": "in_service",
        "source_status": "Commissioned 15 January 2025",
        "status_as_of": "2025-01-15",
        "commissioned_or_inducted_date": "2025-01-15",
        "retired_or_decommissioned_date": "Not documented",
        "quantity": 1,
        "quantity_min": 1,
        "quantity_max": 1,
        "quantity_raw": "1 named submarine",
        "quantity_values": "[1]",
        "role_purpose": "Frontline conventional attack submarine.",
        "specifications": "Not documented",
        "dimensions": "Not documented",
        "make_manufacturer": "Mazagon Dock Shipbuilders Limited / Indian Navy Warship Design Bureau",
        "country_of_origin": "India",
        "operators": "Indian Navy",
        "notes": "Official commissioning supplement; detailed technical fields remain source-dependent.",
        "claim_id": "pib_ins_surat_nilgiri_vaghsheer",
    },
    {
        "system_name": "INS Arnala",
        "branch": "Indian Navy",
        "domain": "ships and submarines",
        "category": "Anti-submarine warfare shallow-water craft",
        "status": "in_service",
        "source_status": "Commissioned 18 June 2025",
        "status_as_of": "2025-06-18",
        "commissioned_or_inducted_date": "2025-06-18",
        "retired_or_decommissioned_date": "Not documented",
        "quantity": 1,
        "quantity_min": 1,
        "quantity_max": 1,
        "quantity_raw": "1 named craft",
        "quantity_values": "[1]",
        "role_purpose": "Sub-surface surveillance and interdiction, search and rescue, and low-intensity maritime operations.",
        "specifications": '{"propulsion": "Diesel engine-waterjet"}',
        "dimensions": '{"length": "77 m", "gross_tonnage": ">1,490 tonnes"}',
        "make_manufacturer": "Garden Reach Shipbuilders and Engineers",
        "country_of_origin": "India",
        "operators": "Indian Navy",
        "notes": "Official commissioning and capability supplement.",
        "claim_id": "pib_ins_arnala",
    },
    {
        "system_name": "INS Nistar",
        "branch": "Indian Navy",
        "domain": "ships and submarines",
        "category": "Diving support vessel",
        "status": "in_service",
        "source_status": "Commissioned 18 July 2025",
        "status_as_of": "2025-07-18",
        "commissioned_or_inducted_date": "2025-07-18",
        "retired_or_decommissioned_date": "Not documented",
        "quantity": 1,
        "quantity_min": 1,
        "quantity_max": 1,
        "quantity_raw": "1 named vessel",
        "quantity_values": "[1]",
        "role_purpose": "Deep-sea saturation diving and submarine rescue operations.",
        "specifications": '{"indigenous_content": ">80%"}',
        "dimensions": "Not documented",
        "make_manufacturer": "Hindustan Shipyard Limited",
        "country_of_origin": "India",
        "operators": "Indian Navy",
        "notes": "Official commissioning supplement.",
        "claim_id": "pib_ins_nistar",
    },
    {
        "system_name": "INS Tamal",
        "branch": "Indian Navy",
        "domain": "ships and submarines",
        "category": "Project 1135.6/Tushil-class stealth frigate",
        "status": "in_service",
        "source_status": "Commissioned 1 July 2025",
        "status_as_of": "2025-07-01",
        "commissioned_or_inducted_date": "2025-07-01",
        "retired_or_decommissioned_date": "Not documented",
        "quantity": 1,
        "quantity_min": 1,
        "quantity_max": 1,
        "quantity_raw": "1 named ship",
        "quantity_values": "[1]",
        "role_purpose": "Multi-role stealth frigate.",
        "specifications": "Not documented",
        "dimensions": "Not documented",
        "make_manufacturer": "Yantar Shipyard",
        "country_of_origin": "Russia",
        "operators": "Indian Navy",
        "notes": "Official commissioning supplement.",
        "claim_id": "pib_ins_tamal",
    },
    {
        "system_name": "INS Udaygiri",
        "branch": "Indian Navy",
        "domain": "ships and submarines",
        "category": "Project 17A stealth frigate",
        "status": "in_service",
        "source_status": "Commissioned 26 August 2025",
        "status_as_of": "2025-08-26",
        "commissioned_or_inducted_date": "2025-08-26",
        "retired_or_decommissioned_date": "Not documented",
        "quantity": 1,
        "quantity_min": 1,
        "quantity_max": 1,
        "quantity_raw": "1 named ship",
        "quantity_values": "[1]",
        "role_purpose": "Frontline stealth frigate.",
        "specifications": "Not documented",
        "dimensions": "Not documented",
        "make_manufacturer": "Mazagon Dock Shipbuilders Limited",
        "country_of_origin": "India",
        "operators": "Indian Navy",
        "notes": "Official commissioning supplement.",
        "claim_id": "pib_ins_udaygiri_himgiri",
    },
    {
        "system_name": "INS Himgiri",
        "branch": "Indian Navy",
        "domain": "ships and submarines",
        "category": "Project 17A stealth frigate",
        "status": "in_service",
        "source_status": "Commissioned 26 August 2025",
        "status_as_of": "2025-08-26",
        "commissioned_or_inducted_date": "2025-08-26",
        "retired_or_decommissioned_date": "Not documented",
        "quantity": 1,
        "quantity_min": 1,
        "quantity_max": 1,
        "quantity_raw": "1 named ship",
        "quantity_values": "[1]",
        "role_purpose": "Advanced guided-missile frigate.",
        "specifications": '{"armament": "Barak 8 and BrahMos missiles"}',
        "dimensions": '{"length": "nearly 149 m", "displacement": "6,670 tonnes"}',
        "make_manufacturer": "Garden Reach Shipbuilders and Engineers",
        "country_of_origin": "India",
        "operators": "Indian Navy",
        "notes": "Official commissioning and capability supplement.",
        "claim_id": "pib_ins_udaygiri_himgiri",
    },
]
