import Link from "next/link";
import { PageHeader, PageShell } from "@/components/PageShell";
import { CollectionToolbar } from "@/components/CollectionToolbar";
import { Pagination } from "@/components/Pagination";
import { parseCollectionQuery } from "@/lib/domain/query";
import { listPublicEntities } from "@/lib/repositories/collections";
import { prisma } from "@/lib/db";
export const dynamic = "force-dynamic";
export default async function OperationsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) { const raw = await searchParams; const query = parseCollectionQuery(raw); const result = await listPublicEntities("Operation", query, prisma); const params = new URLSearchParams(Object.entries(raw).flatMap(([key, value]) => value ? [[key, Array.isArray(value) ? value[0] : value]] : [])); const categories = ["combat", "evacuation", "humanitarian", "peacekeeping", "maritime-security", "rescue", "battle", "event", "other"]; return <PageShell><PageHeader title="Operations" description="Reviewed combat, rescue, and humanitarian records." /><div className="mb-8"><CollectionToolbar fields={[{ key: "category", label: "Category", options: categories }]} /></div><p className="mb-4 text-sm text-muted-foreground">{result.total} reviewed records</p><div className="space-y-3">{result.items.map((operation) => <Link key={operation.id} href={operation.href} className="block rounded-lg border border-border/60 bg-card p-5 transition-colors hover:border-primary/60"><p className="text-xs uppercase text-primary">{operation.facts[0]?.value}</p><h2 className="mt-2 text-xl font-semibold">{operation.title}</h2><p className="mt-2 text-sm text-muted-foreground">{operation.summary}</p></Link>)}</div>{result.items.length === 0 && <p className="mt-6 rounded-lg border border-dashed p-8 text-center text-muted-foreground">No reviewed operations are available.</p>}<div className="mt-8"><Pagination page={result.page} pageCount={result.pageCount} params={params} /></div></PageShell>; }
